# Generated by Django 3.2.10 on 2022-02-05 13:59

from django.db import migrations, models
import django.db.models.deletion
import transaction.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=40)),
                ('agent_account_number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0, validators=[transaction.validators.minimum_amount])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agentAuthentication.agent')),
            ],
        ),
    ]
