# Generated by Django 3.2.10 on 2022-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
