# Generated by Django 3.2.10 on 2022-01-24 21:22

from django.db import migrations
import userAuthentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', userAuthentication.models.CustomUserManager()),
            ],
        ),
    ]
