# Generated by Django 3.2.10 on 2022-01-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0003_auto_20220125_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
