# Generated by Django 3.2.10 on 2022-01-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0004_alter_customuser_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
